### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "mubi@example.com",
  "password": "flag1122"
}

### Find a user with a given id
GET http://localhost:3000/auth/7

### Find a user with a given email
GET http://localhost:3000/auth?email=mubi@example.com

#### Delete a user with a given id
DELETE http://localhost:3000/auth/1

### Update a user with a given id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "mubi@example.com",
  "password": "flag1123"
}

### Sign Up a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "secure@example.com",
  "password": "updatedpassword"
}

### Sign In a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "mubi@example.com",
  "password": "flag1122"
}

### Sign Out the user
POST http://localhost:3000/auth/signout

### Get the currently logged in user
GET http://localhost:3000/auth/whoami


### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "MOTO",
  "model": "XLI",
  "year": 2024,
  "mileage": 900000,
  "lng": 60.01,
  "lat": 60.01,
  "price": 780000
}

### Approve a report
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
  "approved": true
}


### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=60.01&lat=60.01&mileage=100000&year=1990


# Orders Ka kaam yaha se shuru ho ga
POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId": 1,
  "reportId": 1,
  "price": 5000
}