### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "user1@example.com",
  "password": "user1password"
}

### Find a user with a given id
GET http://localhost:3000/auth/1

### Find a user with a given email
GET http://localhost:3000/auth?email=test123@example.com

#### Delete a user with a given id
DELETE http://localhost:3000/auth/2

### Update a user with a given id
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "updated@example.com",
  "password": "updatedpassword"
}

### Sign Up a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "secure@example.com",
  "password": "updatedpassword"
}

### Sign In a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "secure@example.com",
  "password": "updatedpassword"
}

### Sign Out the user
POST http://localhost:3000/auth/signout

### Get the currently logged in user
GET http://localhost:3000/auth/whoami


### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1980,
  "mileage": 100000,
  "lng": 45.45,
  "lat": 45.45,
  "price": 500000
}

### Approve a report
PATCH http://localhost:3000/reports/4
Content-Type: application/json

{
  "approved": true
}


### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=45.45&lat=45.45&mileage=100000&year=1980
