### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "hamza123@example.com",
  "password": "hamza4567"
}

### Find a user with a given id
GET http://localhost:3000/auth/1

### Find a user with a given email
GET http://localhost:3000/auth?email=test123@example.com

#### Delete a user with a given id
DELETE http://localhost:3000/auth/2

### Update a user with a given id
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "updated@example.com",
  "password": "updatedpassword"
}

### Sign Up a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "secure@example.com",
  "password": "updatedpassword"
}

### Sign In a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "secure@example.com",
  "password": "updatedpassword"
}

### Sign Out the user
POST http://localhost:3000/auth/signout

### Get the currently logged in user
GET http://localhost:3000/auth/whoami